# Generated by Django 3.2.16 on 2023-01-14 22:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave', models.CharField(max_length=30, verbose_name='Llave identificadora')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('alta', models.BooleanField(default=True, verbose_name='¿Esta de alta?')),
                ('max_consumo', models.DecimalField(decimal_places=7, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('min_consumo', models.DecimalField(decimal_places=7, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_consumo', models.DecimalField(decimal_places=7, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('media_consumo', models.DecimalField(decimal_places=7, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_y_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('consumo', models.DecimalField(decimal_places=7, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('medidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='API.medidor', verbose_name='Medidor')),
            ],
        ),
    ]
