# Generated by Django 3.2.16 on 2023-01-14 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicion',
            options={'ordering': ['medidor__nombre', 'fecha_y_hora'], 'verbose_name': 'Medicion', 'verbose_name_plural': 'Mediciones'},
        ),
        migrations.AlterModelOptions(
            name='medidor',
            options={'ordering': ['nombre'], 'verbose_name': 'Medidor', 'verbose_name_plural': 'Medidores'},
        ),
    ]
