# Generated by Django 3.2.16 on 2023-01-14 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20230114_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='consumo',
            field=models.DecimalField(decimal_places=7, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Consumo (kwh)'),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='max_consumo',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='media_consumo',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='min_consumo',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='total_consumo',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
